### ISSUE TITLE
v0.5 Roadmap

### ISSUE THREAD

**Issue by j20001970** [j20001970/GDMP#42]
## Framework
- [x] Try out `mediapipe::api2` (#57 )

## Vision Tasks
- [x] HolisticLandmarker (#58)

## 🐧 Linux
- [ ] ~~Pipewire backend for CameraHelper~~
- [x] Build with Freedesktop SDK (Flatpak) in CI

## 🍎 macOS
- [x] macOS CPU build
- [ ] ~~CameraHelper backend using either OpenCV or AVFoundation (maybe share code with iOS?)~~

## 🌐 Web
- [x] Web CPU build (#23) (done but most tasks still not work)

## Multiple Architectures
- [x] Android x86_64
- [ ] ~~Linux arm64~~ Postponed due to XNNPACK issues on GCC14
- [ ] ~~Windows arm64~~ Postponed
- [x] macOS arm64

## OpenCV
- [x] Avoid linking entire libraries to reduce size

## Move to CameraServer-based approach
- [x] [Upstream] Enable custom CameraFeed in GDExtension (https://github.com/godotengine/godot/pull/97571)
- [x] Deprecate MediaPipeCameraHelper

**Comment by GeorgeS2019** [comment]
@j20001970 
@Malcolmnixon 
Is this project helpful for the **HolisticLandmarker** works?
https://github.com/purgeme/mediapipe_cpp_lib/blob/master/src/mcl_basic_holistic.cc

**Comment by GeorgeS2019** [comment]
Is holistic Landmark next after we have 10.15

**Comment by j20001970** [comment]
> Is holistic Landmark next after we have v0.10.15 https://github.com/j20001970/GDMP/actions/runs/10896000612

As of v0.10.15, there is still no C++ API like other vision tasks for HolisticLandmarker, only graph class `HolisticLandmarkerGraph` is defined in `holistic_landmarker_graph.cc`. While I do not know if official mediapipe team has plan to implement it, I would create a HolisticLandmarker graph usage demo on GDMP-demo as the completion of all available vision-related use cases if there are still no official task API before the next GDMP release.

**Comment by GeorgeS2019** [comment]
we need to eventually a way from motion capture using godot4 mediapipe to feed directly captured motion to [Godot 4 MotionMatching](https://github.com/GuilhermeGSousa/godot-motion-matching/issues/35)

**Comment by GeorgeS2019** [comment]
Any update to HolisticLandmarker with the latest update?

**Comment by j20001970** [comment]
> Any update to HolisticLandmarker with the latest update?

MediaPipe v0.10.18 has XNNPACK compilation issue on Windows apparently, so we don't update `mediapipe` submodule for now, but that will not prevent the progress of bringing up HolisticLandmarker task.

Currently `MediaPipeGraphBuilder` and `MediaPipeGraphNode` is being worked on, using MediaPipe's `api2` API, might publish the development branch in a few days. HolisticLandmarker graph will be created and configured using these classes, as demonstrated in MediaPipe's test code. There might be other classes that need to polish up before these two classes becomes usable.

**Comment by j20001970** [comment]
Closed with a8874b87c34ebb49edf8b197b0dd57e0846d3d57
